export type Persona='BRAND'|'CREATOR'|'MEDIA'|'LEARN'|'PARTNER';
export type Answers=Record<string,string|string[]>;
export const personas=[{id:'BRAND',title:'I have a brand or company',desc:'Create a story people choose to watch.',label:'For brands'},{id:'CREATOR',title:"I’m a creator or filmmaker",desc:'Make something worth getting lost in.',label:'For creators'},{id:'MEDIA',title:'I own an audience or media network',desc:'Bring original stories to your audience.',label:'For media'},{id:'LEARN',title:'I want to learn the system',desc:'Build your own one-person studio.',label:'For learners'},{id:'PARTNER',title:'I want to partner with MYTHRA',desc:'Help build the next story network.',label:'For partners'}] as const;
type Question={key:string;title:string;options?:string[];multi?:boolean;fields?:string[]};
const q=(key:string,title:string,options:string[],multi=false):Question=>({key,title,options,multi});
export const questions:Record<Persona,Question[]>={
BRAND:[q('goals','What are you trying to achieve?',['Launch something','Build brand awareness','Tell our story differently','Create recurring entertainment','Build an original character or IP','Experiment with AI-native storytelling','Not sure yet']),q('projectType','What would you like us to create?',['Original branded film','Recurring episodic series','Social-first cinematic campaign','Character / mascot / IP','Product story','Brand documentary','Help us develop the concept']),q('stage','What stage are you at?',['Just exploring','Have an idea','Have a brief','Ready to produce','Already producing content']),q('companyType','What kind of organization are you?',['Startup','SME','Large brand','Agency','Entertainment company','NGO / institution','Other']),q('budgetRange','What scope do you have in mind?',['Exploring','<$5K','$5K–$15K','$15K–$50K','$50K+'])],
CREATOR:[q('goals','What do you want to build?',['Original film','Series','YouTube channel','AI-native studio','Existing story/IP','Commercial projects']),q('role','What best describes you?',['Writer','Director','YouTuber','AI filmmaker','Editor','Producer','Creative entrepreneur','Studio/team']),q('support','What are you looking for from MYTHRA?',['Collaborate on a story','Access MYTHRA workflows','Join production projects','Learn the Drama Method','Distribution','Mentorship / community','Licensing']),q('experienceLevel','Where are you in your journey?',['Just starting','Already producing','100K+ audience','1M+ audience','Professional studio/team'])],
MEDIA:[q('platforms','Where does your audience live?',['Facebook pages','YouTube channels','TikTok accounts','Instagram network','Website/media network','Creator network','Email/community audience'],true),q('audienceSize','What is your combined audience?',['Under 100K','100K–1M','1M–10M','10M–100M','100M+']),{key:'territory',title:'Which audiences could we reach?',fields:['Audience countries','Audience languages']},q('support','How would you like to work together?',['Localized stories','Dubbing','Translation','Distribution partnership','Revenue share','Licensing','Co-production','Exclusive territory'])],
LEARN:[q('goals','What do you most want to learn?',['AI filmmaking','Story development','Character consistency','Storyboarding','Video generation','AI editing','Localization','YouTube distribution','Full one-person studio workflow'],true),q('ambition','What are you trying to become?',['AI creator','Filmmaker','YouTuber','Creative agency','One-person studio','Content entrepreneur']),q('experienceLevel','What level are you at?',['Beginner','Already using AI tools','Already publishing videos','Professional creator','Studio/team'])],
PARTNER:[q('partnershipType','What kind of partnership are you exploring?',['Investment','Film financing','Technology','Distribution','Media partnership','IP licensing','Territory partnership','Brand partnership','Strategic collaboration']),q('resources','What can you bring to the table?',['Capital','Technology','Audience','Distribution','IP','Production resources','Brand relationships','Talent network'],true),{key:'organization',title:'Tell us about your organization.',fields:['Organization','Role','Website','Message (optional)']}]};
// Replace each metric with verified analytics before production launch.
export const mythraProof={verified:false,runtime:'27–28',productionTime:'<72',experimentalCost:'<$1,000',views:[{value:15,suffix:'M',label:'Official YouTube channel'},{value:4,suffix:'M',label:'Official Facebook page'},{value:300,suffix:'M+',label:'International / translated distribution'},{value:5,suffix:'M',label:'Translated YouTube audience'}]};
export const nurture:Record<Persona,string[]>={BRAND:['Case Study','Drama Method','Behind the Scenes','Brand Story Concept','Collaboration Call'],CREATOR:['Case Study','Workflow','Creator Story','MYTHRA Lab','Application'],MEDIA:['Case Study','Localization Model','Distribution Opportunity','Partnership Example','Conversation'],LEARN:['Case Study','Studio Workflow','Free Insight','Creator Program','Join'],PARTNER:['Vision','Case Study','Opportunity','Partnership Areas','Founder Conversation']};
export function intelligence(persona:Persona,a:Answers,contact:Record<string,string>={}){let score=0;const tags=['MYTHRA_'+persona];if(persona==='BRAND'&&['$15K–$50K','$50K+'].includes(String(a.budgetRange))){score+=30;tags.push('MYTHRA_BRAND_HIGH_VALUE')}if(persona==='MEDIA'){if(['10M–100M','100M+'].includes(String(a.audienceSize))){score+=25;tags.push('MYTHRA_MEDIA_10M')}else if(a.audienceSize==='1M–10M')tags.push('MYTHRA_MEDIA_1M')}if(a.stage==='Ready to produce'){score+=20;tags.push('MYTHRA_READY_TO_PRODUCE')}if(a.partnershipType==='Investment'){score+=20;tags.push('MYTHRA_PARTNER_INVESTMENT')}if(a.partnershipType==='Distribution')tags.push('MYTHRA_PARTNER_DISTRIBUTION');if(contact.company||contact.website||a.Organization)score+=15;if((contact.message||String(a['Message (optional)']||'')).length>=60)score+=10;if(persona==='CREATOR'&&a.experienceLevel==='1M+ audience')score+=15;if(persona==='CREATOR'&&['1M+ audience','Professional studio/team'].includes(String(a.experienceLevel)))tags.push('MYTHRA_CREATOR_PRO');if(persona==='LEARN')tags.push(a.experienceLevel==='Beginner'?'MYTHRA_LEARN_BEGINNER':'MYTHRA_LEARN_PRO');return {score,category:score>=60?'priority':score>=30?'qualified':'nurture',tags,nurtureTrack:nurture[persona]};}
export function recommendation(p:Persona,a:Answers){if(p==='BRAND')return String(a.projectType||'Original Branded Story');if(p==='CREATOR')return a.support==='Collaborate on a story'?'Story Incubator':a.support==='Join production projects'?'Production Collaboration':a.support==='Learn the Drama Method'?'Drama Method Access':'MYTHRA Creator Lab';if(p==='MEDIA')return String(a.support||'Distribution Partnership');if(p==='LEARN')return a.experienceLevel==='Beginner'?'MYTHRA Lab · Foundation':'MYTHRA Studio Access';return String(a.partnershipType||'Strategic Collaboration');}
export const method=['Audience psychology','Drama Method','Story engine','Character consistency','AI production','Long-form editing','Audience testing','Translation','Localization','Distribution network','Feedback','Next story'];
export const methodDescriptions=['Understand what your audience feels, fears and hopes for.','Build tension through a human choice with something at stake.','Develop an original premise into a world that can sustain a story.','Keep character identity, costume and behavior coherent across scenes.','Turn a deliberate storyboard into controlled visual and audio production.','Shape pacing, sound and emotion into a film that holds attention.','Read the audience response to learn which story choices resonate.','Carry the meaning of the story into a new language.','Adapt voices and cultural context with care for each audience.','Bring the right version of the story to the right channels.','Use response to refine the creative decisions, not just the metrics.','Carry what we learned into the next original story.'];
