// Central Offer, Pricing, and Product Catalog for MYTHRA
// Editable via config/admin layer. Defaults to USD.

export interface OfferTier {
  id: string;
  code: string;
  name: string;
  persona: 'YOU' | 'FILMMAKER' | 'STUDIOS';
  price: number;
  priceDisplay: string;
  isStartingPrice?: boolean;
  isRecommended?: boolean;
  tagline: string;
  description: string;
  features: string[];
  deliverables: string[];
  turnaround: string;
  revisions: string;
  voiceCloningIncluded: boolean;
  commercialUsageIncluded: boolean;
  checkoutType: 'instant' | 'deposit' | 'application' | 'consultation' | 'free';
  ctaText: string;
  ctaHref: string;
}

export interface AddOn {
  id: string;
  name: string;
  price: number | 'custom';
  priceDisplay: string;
  description: string;
  applicableTiers: string[];
}

export interface OffersConfig {
  you: OfferTier[];
  youAddOns: AddOn[];
  filmmaker: OfferTier[];
  studios: OfferTier[];
}

export const mythraOffers: OffersConfig = {
  you: [
    {
      id: 'you-moment',
      code: 'MYTHRA_MOMENT',
      name: 'MYTHRA MOMENT',
      persona: 'YOU',
      price: 79,
      priceDisplay: '$79',
      tagline: 'A cinematic snapshot',
      description: '20–30 second template-led cinematic scene starring one authorized person. Perfect for gifts, memorable social moments, and personal milestones.',
      features: [
        '20–30 second template-led cinematic scene',
        'One authorized person',
        'Face likeness from approved high-res photos',
        'Name & title personalization',
        'Licensed cinematic score & sound design',
        '1080p full HD master delivery',
        '1 consolidated revision round',
        'No cloned voice (cinematic narration or text only)',
      ],
      deliverables: ['1080p Master Video (16:9 or 9:16)'],
      turnaround: '3–5 business days',
      revisions: '1 round',
      voiceCloningIncluded: false,
      commercialUsageIncluded: false,
      checkoutType: 'instant',
      ctaText: 'Create Moment · $79',
      ctaHref: '/you/start?tier=you-moment',
    },
    {
      id: 'you-trailer',
      code: 'MYTHRA_TRAILER',
      name: 'MYTHRA TRAILER',
      persona: 'YOU',
      price: 299,
      priceDisplay: '$299',
      isRecommended: true,
      tagline: 'Your life as a blockbuster film',
      description: '60–90 second bespoke movie trailer with 5–8 cinematic story beats, custom screenplay premise, authorized face, and optional authorized voice clone.',
      features: [
        '60–90 second personalized movie trailer',
        'Custom story premise based on your questionnaire',
        'One authorized lead character',
        'Authorized face & optional authorized voice clone',
        '5 to 8 cinematic story beats & custom world',
        'Custom voiceover, bespoke score & full sound design',
        '1080p landscape master + vertical social cut',
        '2 consolidated revision rounds',
      ],
      deliverables: ['1080p 16:9 Cinematic Master', '1080p 9:16 Vertical Cut', 'Digital Film Poster Stills'],
      turnaround: '7–10 business days',
      revisions: '2 rounds',
      voiceCloningIncluded: true,
      commercialUsageIncluded: false,
      checkoutType: 'instant',
      ctaText: 'Create My Trailer · $299',
      ctaHref: '/you/start?tier=you-trailer',
    },
    {
      id: 'you-story',
      code: 'MYTHRA_STORY',
      name: 'MYTHRA STORY',
      persona: 'YOU',
      price: 1500,
      priceDisplay: 'From $1,500',
      isStartingPrice: true,
      tagline: 'A bespoke 3–5 minute short film',
      description: 'Custom screenplay, storyboard, and original world design for 1–2 authorized characters. Requires creative feasibility review prior to 50% deposit.',
      features: [
        '3–5 minute bespoke cinematic short film',
        'Story interview or detailed creative questionnaire',
        'Custom screenplay and full storyboard approval',
        '1 or 2 authorized characters',
        'Authorized face & optional authorized voice',
        'Bespoke world, scenes, score, edit & title design',
        '2 comprehensive revision rounds',
        '50% deposit after scope approval',
      ],
      deliverables: ['4K/1080p Master Cut', 'Vertical Teaser', 'Screenplay PDF', 'Key Art Gallery'],
      turnaround: '2–4 weeks',
      revisions: '2 rounds',
      voiceCloningIncluded: true,
      commercialUsageIncluded: false,
      checkoutType: 'deposit',
      ctaText: 'Start Story Brief · From $1,500',
      ctaHref: '/you/start?tier=you-story',
    },
    {
      id: 'you-legacy',
      code: 'MYTHRA_LEGACY',
      name: 'MYTHRA LEGACY',
      persona: 'YOU',
      price: 5000,
      priceDisplay: 'From $5,000',
      isStartingPrice: true,
      tagline: 'An enduring cinematic heirloom',
      description: '8–15 minute premium life story, founder documentary, wedding film, or family tribute with dedicated creative director and research.',
      features: [
        '8–15 minute cinematic documentary or heirloom film',
        'Dedicated Creative Director research call',
        'Full screenplay, character/world bible & production plan',
        'Multiple authorized characters where feasible',
        'Archival photo/video restoration integration',
        'Custom orchestral score & cinema-grade sound mix',
        'Custom rights & archival packaging',
        'Milestone billing (30% / 40% / 30%)',
      ],
      deliverables: ['4K Cinema Master (ProRes/H.264)', 'Trailer Cut', 'Archival Hard Copy Box', 'Production Bible'],
      turnaround: '4–8 weeks',
      revisions: 'Custom milestone reviews',
      voiceCloningIncluded: true,
      commercialUsageIncluded: false,
      checkoutType: 'application',
      ctaText: 'Inquire for Legacy · From $5,000',
      ctaHref: '/you/start?tier=you-legacy',
    },
  ],

  youAddOns: [
    {
      id: 'addon-extra-star',
      name: 'Additional Authorized Star',
      price: 149,
      priceDisplay: '+$79 (Moment) / +$149 (Trailer)',
      description: 'Include an additional consenting co-star with verified likeness authorization.',
      applicableTiers: ['you-moment', 'you-trailer', 'you-story', 'you-legacy'],
    },
    {
      id: 'addon-extra-language',
      name: 'Additional Language / Dub',
      price: 49,
      priceDisplay: '+$49 / language',
      description: 'Fully translated voice narration or AI dub with matched lip performance.',
      applicableTiers: ['you-trailer', 'you-story', 'you-legacy'],
    },
    {
      id: 'addon-priority-delivery',
      name: 'Priority Production Delivery',
      price: 'custom',
      priceDisplay: 'Quoted on capacity',
      description: 'Fast-tracked queue position subject to director schedule availability.',
      applicableTiers: ['you-moment', 'you-trailer'],
    },
    {
      id: 'addon-commercial-license',
      name: 'Commercial & Advertising License',
      price: 'custom',
      priceDisplay: 'Custom License',
      description: 'Permits commercial broadcast, paid ads, or corporate promotion (priced separately from personal use).',
      applicableTiers: ['you-moment', 'you-trailer', 'you-story', 'you-legacy'],
    },
  ],

  filmmaker: [
    {
      id: 'film-blueprint',
      code: 'MYTHRA_BLUEPRINT',
      name: 'THE ONE-PERSON STUDIO BLUEPRINT',
      persona: 'FILMMAKER',
      price: 0,
      priceDisplay: 'Free Access',
      tagline: 'The complete high-level system',
      description: 'A 45–60 minute intensive workshop breakdown covering the complete 12-step Drama Method and AI production pipeline.',
      features: [
        '45–60 minute full production walkthrough',
        'The 12-Step Drama Method architecture',
        'Tool-agnostic production pipeline diagram',
        'Character consistency & story engine framework',
        'Cost breakdown from the Genesis experiment',
      ],
      deliverables: ['Video Workshop Access', 'Studio Blueprint PDF Checklist'],
      turnaround: 'Instant Access',
      revisions: 'N/A',
      voiceCloningIncluded: false,
      commercialUsageIncluded: false,
      checkoutType: 'free',
      ctaText: 'Access Free Blueprint',
      ctaHref: '/filmmaker/start?tier=film-blueprint',
    },
    {
      id: 'film-starter',
      code: 'MYTHRA_STARTER',
      name: 'MYTHRA STARTER',
      persona: 'FILMMAKER',
      price: 149,
      priceDisplay: '$149',
      tagline: 'Self-paced fundamentals',
      description: 'Comprehensive video training, prompt architectures, story bibles, and workflow templates to build your first AI short film.',
      features: [
        'Self-paced 8-module comprehensive curriculum',
        'Story, character, storyboard, image, motion & sound modules',
        'Production templates, shot lists & character bible sheets',
        '1-year full platform access & future course updates',
        'Independent pacing with zero fluff or tool lock-in',
      ],
      deliverables: ['8 Modular Course Tracks', 'Notion & PDF Production System', 'Prompt & Workflow Library'],
      turnaround: 'Instant Access',
      revisions: 'Self-paced',
      voiceCloningIncluded: false,
      commercialUsageIncluded: false,
      checkoutType: 'instant',
      ctaText: 'Enroll in Starter · $149',
      ctaHref: '/filmmaker/start?tier=film-starter',
    },
    {
      id: 'film-cohort',
      code: 'MYTHRA_COHORT',
      name: 'MYTHRA FILMMAKER COHORT',
      persona: 'FILMMAKER',
      price: 749,
      priceDisplay: '$749 Founding ($997 Standard)',
      isRecommended: true,
      tagline: '6-Week Live Production Accelerator',
      description: 'Weekly live production sessions, hands-on feedback, and a structured sprint where you complete and publish your own portfolio film or trailer.',
      features: [
        '6-week intensive live cohort with weekly production sessions',
        'Direct feedback on screenplay, character bibles & rough cuts',
        'Master character & world consistency across multi-scene edits',
        'Sound design, custom scoring & AI voice synthesis mastery',
        'Complete and publish 1 finished portfolio film or trailer',
        'Cohort community workspace during program + 90 days access',
        'Tool compute costs clearly disclosed (~$50–$100 estimated)',
      ],
      deliverables: ['Live Weekly Sessions & Recordings', 'Director Project Reviews', 'Published Portfolio Film', 'Alumni Network Access'],
      turnaround: '6 Weeks (Next cohort starting soon)',
      revisions: 'Weekly structured feedback',
      voiceCloningIncluded: true,
      commercialUsageIncluded: false,
      checkoutType: 'instant',
      ctaText: 'Join Cohort · $749',
      ctaHref: '/filmmaker/start?tier=film-cohort',
    },
    {
      id: 'film-accelerator',
      code: 'MYTHRA_ACCELERATOR',
      name: 'MYTHRA STUDIO ACCELERATOR',
      persona: 'FILMMAKER',
      price: 2500,
      priceDisplay: 'From $2,500',
      isStartingPrice: true,
      tagline: 'For working creators, agencies & small teams',
      description: 'Application-only 8–12 week program to build a repeatable production pipeline, team workflow, and commercial client offer.',
      features: [
        '8–12 week private agency/creator mentorship',
        'Build a repeatable multi-person production pipeline',
        'Quality control, client delivery & rights governance SOPs',
        'Portfolio polishing & commercial pitch decks',
        'Distribution strategy & audience testing frameworks',
        'No false income guarantees — purely tactical execution',
      ],
      deliverables: ['Private Studio Pipeline Setup', 'Commercial Asset Library', 'Client Contract & Delivery Templates'],
      turnaround: '8–12 Weeks',
      revisions: 'Direct 1-on-1 pipeline reviews',
      voiceCloningIncluded: true,
      commercialUsageIncluded: true,
      checkoutType: 'application',
      ctaText: 'Apply for Accelerator',
      ctaHref: '/filmmaker/start?tier=film-accelerator',
    },
  ],

  studios: [
    {
      id: 'studio-concept-sprint',
      code: 'STUDIO_SPRINT',
      name: 'STORY CONCEPT SPRINT',
      persona: 'STUDIOS',
      price: 2500,
      priceDisplay: '$2,500',
      tagline: 'Strategic story development workshop',
      description: 'Strategic audience discovery, core premise design, format bible, visual reference direction, and treatment. 100% credited toward production over $15K within 30 days.',
      features: [
        'Strategic discovery workshop with MYTHRA creative leads',
        'Audience psychology & story opportunity mapping',
        'Core premise, format, tone & reference direction',
        'Initial creative treatment & visual mood boards',
        'Can be credited toward a $15,000+ production if contracted within 30 days',
      ],
      deliverables: ['Story Concept Bible', 'Visual Treatment Deck', 'Production Budget & Feasibility Plan'],
      turnaround: '5–7 business days',
      revisions: '1 review session',
      voiceCloningIncluded: false,
      commercialUsageIncluded: true,
      checkoutType: 'deposit',
      ctaText: 'Request Concept Sprint · $2,500',
      ctaHref: '/studios/start?tier=studio-concept-sprint',
    },
    {
      id: 'studio-pilot',
      code: 'STUDIO_PILOT',
      name: 'SOCIAL DRAMA PILOT',
      persona: 'STUDIOS',
      price: 7500,
      priceDisplay: 'From $7,500',
      isStartingPrice: true,
      isRecommended: true,
      tagline: '45–90s Proof-of-concept or Branded Story Pilot',
      description: 'Complete concept, screenplay, visual direction, AI-native production, sound design, and master delivery. Designed to test audience engagement.',
      features: [
        '45–90 second premium branded drama or POC pilot',
        'Original concept, screenplay & visual design',
        'AI-native production, sound design & color finish',
        '1 master format (16:9) plus agreed social cuts (9:16 / 1:1)',
        'Audience hook testing & engagement recommendations',
      ],
      deliverables: ['16:9 4K Master', '9:16 Social Cut', 'Audio Stems & Subtitles', 'Audience Test Brief'],
      turnaround: '2–3 weeks',
      revisions: '2 rounds',
      voiceCloningIncluded: true,
      commercialUsageIncluded: true,
      checkoutType: 'consultation',
      ctaText: 'Commission a Pilot · From $7,500',
      ctaHref: '/studios/start?tier=studio-pilot',
    },
    {
      id: 'studio-short',
      code: 'STUDIO_SHORT',
      name: 'BRANDED SHORT FILM',
      persona: 'STUDIOS',
      price: 15000,
      priceDisplay: 'From $15,000',
      isStartingPrice: true,
      tagline: '3–5 Minute Standalone Cinema Experience',
      description: 'Comprehensive brand storytelling, original script, character & world bible, high-fidelity AI-native cinematic production, and full broadcast audio.',
      features: [
        '3–5 minute original branded short film',
        'Full brand alignment strategy & screenplay',
        'Proprietary character/world consistency system',
        'Cinema-grade sound mix, Foley & original score',
        'Distribution strategy & cutdown campaign assets',
        'Localization and multi-language dubbing available as add-on',
      ],
      deliverables: ['4K Cinema Master (ProRes)', 'Social Teaser Suite (3 cuts)', 'Key Visual Stills', 'Screenplay & Asset Bible'],
      turnaround: '3–5 weeks',
      revisions: '3 milestone reviews',
      voiceCloningIncluded: true,
      commercialUsageIncluded: true,
      checkoutType: 'consultation',
      ctaText: 'Scope a Branded Film · From $15,000',
      ctaHref: '/studios/start?tier=studio-short',
    },
    {
      id: 'studio-episodic',
      code: 'STUDIO_EPISODIC',
      name: 'EPISODIC STORY SYSTEM',
      persona: 'STUDIOS',
      price: 30000,
      priceDisplay: 'From $30,000',
      isStartingPrice: true,
      tagline: 'A Scalable Story World & Series Pilot',
      description: 'Series bible, reusable character & asset system, pilot episode, and 2 additional episodes (or equivalent scoped package).',
      features: [
        'Complete episodic series bible & format architecture',
        'Pilot episode + 2 additional episodes (or equivalent scope)',
        'Reusable character, voice & environment digital asset system',
        'High-velocity recurring production pipeline for brand/IP',
        'Territory and licensing rights scoped transparently',
      ],
      deliverables: ['Series Master Files (3 Episodes)', 'Master World & Character Bible', 'Recurring Production SLA'],
      turnaround: '6–8 weeks',
      revisions: 'Milestone reviews per episode',
      voiceCloningIncluded: true,
      commercialUsageIncluded: true,
      checkoutType: 'consultation',
      ctaText: 'Build a Story System · From $30,000',
      ctaHref: '/studios/start?tier=studio-episodic',
    },
    {
      id: 'studio-coproduction',
      code: 'STUDIO_COPROD',
      name: 'LONG-FORM / ORIGINAL IP / CO-PRODUCTION',
      persona: 'STUDIOS',
      price: 50000,
      priceDisplay: 'From $50,000',
      isStartingPrice: true,
      tagline: 'Original studio slate & IP co-production',
      description: 'Strategic co-production, IP adaptation (novels, games, comics), and theatrical/streaming AI-native long-form drama with milestone governance.',
      features: [
        'Full 20–60+ minute narrative adaptation or original IP',
        'Executive creative direction & global distribution architecture',
        'Custom milestone finance & governance agreement',
        'Multi-language localization & worldwide distribution rollout',
        'No immediate checkout — executive conversation required',
      ],
      deliverables: ['Full Master Film Package', 'Worldwide Localization Kit', 'IP Rights & Distribution Package'],
      turnaround: 'Custom Timeline',
      revisions: 'Executive review milestones',
      voiceCloningIncluded: true,
      commercialUsageIncluded: true,
      checkoutType: 'consultation',
      ctaText: 'Executive Consultation · From $50,000',
      ctaHref: '/studios/start?tier=studio-coproduction',
    },
  ],
};
